### PR TITLE
[talk][sign up][Pinglei Guo] Raft & Ceph

### PR DESCRIPTION
**Pull request by at15**
Pinglei Guo piguo@ucsc.edu sing up for the following lighting talks
- Raft on 10/14
- Ceph on 10/28

@palvaro I have some concern for using PR and the talk itself. 
- when we chose a specific topic from a paper, there might be overlap, it could happen that four pepople's talk have too much in common.
- some students may not know GitHub or PR, we should have some links in README
- there will be merge conflict when more than one student sign up for the same paper since the schedule doc only has one line for each paper. Using another file like `talk.md` may solve it, note paper name need to be there, we only fill the name. Git can auto merge (I guess) when we write our name on different lines.
- a template for PR and commit message may also be needed, though it's OK for every one just say `Update Readings` but it's hard to tell what papers they are signing up for 
- add issue label `talk` in case there are other type of issues

A sample for `talk.md`

```
# Talks

## 09/26 Time and Clocks

..

## 10/14 Raft

- Pinglei Guo
- Leiping Guo
- Guo Guo


...
```

Also some proposal
- add github link or personal website link when signup, in case we want to know the speaker before the class
- add link to slide (if there is one), though we don't have time for Q&A, reading slides before talk can help other students understand and may help avoiding duplicated content.
- use [gitter](https://gitter.im) or piazza for after class discussion, IMO easychair is not a good place for discuss when we have so many better options.

### CODE REVIEW

**Comment by at15** [comment]
@mshavlovsky pls merge this PR before merging other Ceph related PRs, otherwise I need to update my branch again. 

Other PRs that contains Ceph are #9 #10 #11 #14   (we are 100% slug indeed .... slot overflow)

**Comment by palvaro** [comment]
I thought using PRs was your idea :)
I think Michael plans to switch over to a google doc to manage these allocations.  I am not concerned about overlap in the talks.  if everyone chooses to spend their 5 minutes talking about the same thing, that is an interesting result in itself!  Regarding how to use github, this is a subject that I am confident graduate students can figure out on their own.

**Comment by at15** [comment]
@palvaro yeah it was my idea 😅  ..... I thought it can reduce the risk of editing other people's sign up. 

btw: can my PR be merged 

And what do we do about slot overflow, there are already 5 people signing up for Ceph, FIFO?

**Comment by mshavlovsky** [comment]
@at15 I've just sent a link to a spreadsheet for sign ups. Can you add your preferences over there? I will synch it with the original one.

**Comment by at15** [comment]
@mshavlovsky got the link, sorry for the inconvenience caused by my proposal. Update my preference in the spreadsheet. I will close this PR now.

**Pull request closed without merging**
