### PR TITLE
Update readings.md

### PR DESCRIPTION
**Pull request by czheo**
Sign up for lightning talks

### CODE REVIEW

**Comment by czheo** [comment]
@palvaro You may want to merge PRs into master quickly. Otherwise, conflicts could happen for other later coming students.

**Comment by at15** [comment]
@czheo see #6 we may use a separated file so git can auto merge without conflict.

**Comment by Fayyang0102** [comment]
Sign up for lightning talks
Dynamo & Ceph

**Comment by at15** [comment]
@Fayyang0102 you should send another pull request instead of comment on existing one. 
- fork the repo
- add yourself by modifying `readings.md` (you can edit it online if you don't know how to clone and edit it locally)
- send the pull request 

you can have a look at github help about how to fork and make a PR
- https://help.github.com/articles/about-pull-requests/
- https://help.github.com/articles/creating-a-pull-request-from-a-fork/
- https://help.github.com/articles/fork-a-repo/

**Pull request merged**
